// <auto-generated />
using System;
using ClubApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubApp.Migrations
{
    [DbContext(typeof(ClubAppsContext))]
    partial class ClubAppsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClubApp.Models.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ClauseBudget")
                        .HasColumnType("float")
                        .HasColumnName("clause_budget");

                    b.Property<double?>("MainBudget")
                        .HasColumnType("float")
                        .HasColumnName("main_budget");

                    b.Property<byte[]>("UpdatedAt")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__budget__3213E83F8E13C09C");

                    b.HasIndex(new[] { "UserId" }, "UQ__budget__B9BE370E55828646")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("budget", (string)null);
                });

            modelBuilder.Entity("ClubApp.Models.ClubUserApp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Lema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ClubApp.Models.Cup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool?>("Finished")
                        .HasColumnType("bit")
                        .HasColumnName("finished");

                    b.Property<string>("NameCup")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name_cup");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__cups__3213E83FE8CC537F");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("cups", (string)null);
                });

            modelBuilder.Entity("ClubApp.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CupId")
                        .HasColumnType("int")
                        .HasColumnName("cup_id");

                    b.Property<string>("FinishedByUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("finished_by_user_id");

                    b.Property<bool?>("IsFinished")
                        .HasColumnType("bit")
                        .HasColumnName("is_finished");

                    b.Property<int?>("ScoreTeamA")
                        .HasColumnType("int")
                        .HasColumnName("score_team_a");

                    b.Property<int?>("ScoreTeamB")
                        .HasColumnType("int")
                        .HasColumnName("score_team_b");

                    b.Property<int?>("TeamAId")
                        .HasColumnType("int")
                        .HasColumnName("team_a_id");

                    b.Property<int?>("TeamBId")
                        .HasColumnType("int")
                        .HasColumnName("team_b_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__games__3213E83F0DD01ED4");

                    b.HasIndex("CupId");

                    b.HasIndex("FinishedByUserId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.HasIndex("UserId");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("ClubApp.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Amount")
                        .HasColumnType("float")
                        .HasColumnName("amount");

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("created_at");

                    b.Property<int?>("FromTeamId")
                        .HasColumnType("int")
                        .HasColumnName("from_team_id");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int?>("ToPlayerId")
                        .HasColumnType("int")
                        .HasColumnName("to_player_id");

                    b.Property<int?>("ToTeamId")
                        .HasColumnType("int")
                        .HasColumnName("to_team_id");

                    b.HasKey("Id")
                        .HasName("PK__offers__3213E83F30A2986E");

                    b.HasIndex("FromTeamId");

                    b.HasIndex("StatusId");

                    b.HasIndex("ToPlayerId");

                    b.HasIndex("ToTeamId");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("ClubApp.Models.OffersStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK__offers_s__3213E83FD87AD087");

                    b.ToTable("offers_status", (string)null);
                });

            modelBuilder.Entity("ClubApp.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<int?>("DefensiveAwareness")
                        .HasColumnType("int")
                        .HasColumnName("defensive_awareness");

                    b.Property<int?>("Dribling")
                        .HasColumnType("int")
                        .HasColumnName("dribling");

                    b.Property<int?>("Interceptions")
                        .HasColumnType("int")
                        .HasColumnName("interceptions");

                    b.Property<bool?>("IsStarting")
                        .HasColumnType("bit")
                        .HasColumnName("is_starting");

                    b.Property<double?>("MarketValue")
                        .HasColumnType("float")
                        .HasColumnName("market_value");

                    b.Property<string>("OriginalTeam")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("original_team");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("int")
                        .HasColumnName("overall_rating");

                    b.Property<int?>("Pace")
                        .HasColumnType("int")
                        .HasColumnName("pace");

                    b.Property<string>("PhotoSrc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("photo_src");

                    b.Property<string>("Playername")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("playername");

                    b.Property<double?>("PositionX")
                        .HasColumnType("float")
                        .HasColumnName("position_x");

                    b.Property<double?>("PositionY")
                        .HasColumnType("float")
                        .HasColumnName("position_y");

                    b.Property<int?>("Potential")
                        .HasColumnType("int")
                        .HasColumnName("potential");

                    b.Property<int?>("Reflects")
                        .HasColumnType("int")
                        .HasColumnName("reflects");

                    b.Property<double?>("ReleaseClause")
                        .HasColumnType("float")
                        .HasColumnName("release_clause");

                    b.Property<int?>("Shooting")
                        .HasColumnType("int")
                        .HasColumnName("shooting");

                    b.Property<int?>("Strenght")
                        .HasColumnType("int")
                        .HasColumnName("strenght");

                    b.Property<int?>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("team_id")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK__players__3213E83F31150BE6");

                    b.HasIndex("TeamId");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("ClubApp.Models.Standing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CupId")
                        .HasColumnType("int")
                        .HasColumnName("cup_id");

                    b.Property<int?>("Draws")
                        .HasColumnType("int")
                        .HasColumnName("draws");

                    b.Property<int?>("GoalsAgainst")
                        .HasColumnType("int")
                        .HasColumnName("goals_against");

                    b.Property<int?>("GoalsFor")
                        .HasColumnType("int")
                        .HasColumnName("goals_for");

                    b.Property<int?>("Losses")
                        .HasColumnType("int")
                        .HasColumnName("losses");

                    b.Property<int?>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<int?>("Wins")
                        .HasColumnType("int")
                        .HasColumnName("wins");

                    b.HasKey("Id")
                        .HasName("PK__standing__3213E83FA9BAAFBC");

                    b.HasIndex("CupId");

                    b.HasIndex("TeamId");

                    b.ToTable("standings", (string)null);
                });

            modelBuilder.Entity("ClubApp.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("created_at");

                    b.Property<string>("OwneruserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("owneruser_id");

                    b.Property<string>("Teamname")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("teamname");

                    b.HasKey("Id")
                        .HasName("PK__teams__3213E83F7A1092A7");

                    b.HasIndex(new[] { "OwneruserId" }, "UQ__teams__85C39ECD42F9721D")
                        .IsUnique()
                        .HasFilter("[owneruser_id] IS NOT NULL");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("ClubApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetId")
                        .HasColumnType("int");

                    b.Property<byte[]>("CreatedAt")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("google_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("role");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83F62C1819B");

                    b.HasIndex("BudgetId");

                    b.HasIndex("TeamId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ClubApp.Models.Budget", b =>
                {
                    b.HasOne("ClubApp.Models.ClubUserApp", "User")
                        .WithOne("Budget")
                        .HasForeignKey("ClubApp.Models.Budget", "UserId")
                        .HasConstraintName("FK__budget__user_id__5629CD9C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClubApp.Models.Cup", b =>
                {
                    b.HasOne("ClubApp.Models.ClubUserApp", "CreatedByUser")
                        .WithMany("Cups")
                        .HasForeignKey("CreatedByUserId")
                        .HasConstraintName("FK__cups__created_by__4F7CD00D");

                    b.HasOne("ClubApp.Models.User", null)
                        .WithMany("Cups")
                        .HasForeignKey("UserId");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ClubApp.Models.Game", b =>
                {
                    b.HasOne("ClubApp.Models.Cup", "Cup")
                        .WithMany("Games")
                        .HasForeignKey("CupId")
                        .HasConstraintName("FK__games__cup_id__5070F446");

                    b.HasOne("ClubApp.Models.ClubUserApp", "FinishedByUser")
                        .WithMany("Games")
                        .HasForeignKey("FinishedByUserId")
                        .HasConstraintName("FK__games__finished___534D60F1");

                    b.HasOne("ClubApp.Models.Team", "TeamA")
                        .WithMany("GameTeamAs")
                        .HasForeignKey("TeamAId")
                        .HasConstraintName("FK__games__team_a_id__5165187F");

                    b.HasOne("ClubApp.Models.Team", "TeamB")
                        .WithMany("GameTeamBs")
                        .HasForeignKey("TeamBId")
                        .HasConstraintName("FK__games__team_b_id__52593CB8");

                    b.HasOne("ClubApp.Models.User", null)
                        .WithMany("Games")
                        .HasForeignKey("UserId");

                    b.Navigation("Cup");

                    b.Navigation("FinishedByUser");

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("ClubApp.Models.Offer", b =>
                {
                    b.HasOne("ClubApp.Models.Team", "FromTeam")
                        .WithMany("OfferFromTeams")
                        .HasForeignKey("FromTeamId")
                        .HasConstraintName("FK__offers__from_tea__4BAC3F29");

                    b.HasOne("ClubApp.Models.OffersStatus", "Status")
                        .WithMany("Offers")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK__offers__status_i__4E88ABD4");

                    b.HasOne("ClubApp.Models.Player", "ToPlayer")
                        .WithMany("Offers")
                        .HasForeignKey("ToPlayerId")
                        .HasConstraintName("FK__offers__to_playe__4D94879B");

                    b.HasOne("ClubApp.Models.Team", "ToTeam")
                        .WithMany("OfferToTeams")
                        .HasForeignKey("ToTeamId")
                        .HasConstraintName("FK__offers__to_team___4CA06362");

                    b.Navigation("FromTeam");

                    b.Navigation("Status");

                    b.Navigation("ToPlayer");

                    b.Navigation("ToTeam");
                });

            modelBuilder.Entity("ClubApp.Models.Player", b =>
                {
                    b.HasOne("ClubApp.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__players__team_id__4AB81AF0");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ClubApp.Models.Standing", b =>
                {
                    b.HasOne("ClubApp.Models.Cup", "Cup")
                        .WithMany("Standings")
                        .HasForeignKey("CupId")
                        .HasConstraintName("FK__standings__cup_i__5441852A");

                    b.HasOne("ClubApp.Models.Team", "Team")
                        .WithMany("Standings")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK__standings__team___5535A963");

                    b.Navigation("Cup");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ClubApp.Models.Team", b =>
                {
                    b.HasOne("ClubApp.Models.ClubUserApp", "Owneruser")
                        .WithOne("Team")
                        .HasForeignKey("ClubApp.Models.Team", "OwneruserId")
                        .HasConstraintName("FK__teams__owneruser__49C3F6B7");

                    b.Navigation("Owneruser");
                });

            modelBuilder.Entity("ClubApp.Models.User", b =>
                {
                    b.HasOne("ClubApp.Models.Budget", "Budget")
                        .WithMany()
                        .HasForeignKey("BudgetId");

                    b.HasOne("ClubApp.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.Navigation("Budget");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ClubApp.Models.ClubUserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ClubApp.Models.ClubUserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClubApp.Models.ClubUserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ClubApp.Models.ClubUserApp", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClubApp.Models.ClubUserApp", b =>
                {
                    b.Navigation("Budget");

                    b.Navigation("Cups");

                    b.Navigation("Games");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ClubApp.Models.Cup", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("ClubApp.Models.OffersStatus", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("ClubApp.Models.Player", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("ClubApp.Models.Team", b =>
                {
                    b.Navigation("GameTeamAs");

                    b.Navigation("GameTeamBs");

                    b.Navigation("OfferFromTeams");

                    b.Navigation("OfferToTeams");

                    b.Navigation("Players");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("ClubApp.Models.User", b =>
                {
                    b.Navigation("Cups");

                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
